### ISSUE TITLE
Are table-based examples working?

### ISSUE THREAD

**Issue by Jungmo** [moskomule/pytorch.rl.learning#3]
I tried Q-learning and sarsa in the table directory.
I have not tested other examples in the table directory but Q-learning and sarsa examples occur below IndexError.

start training
Traceback (most recent call last):
  File "C:/Users/xxx/PycharmProjects/pytorch.rl.learning/predl/table/sarsa.py", line 57, in <module>
    main()
  File "C:/Users/xxx/PycharmProjects/pytorch.rl.learning/predl/table/sarsa.py", line 36, in main
    sarsa9()
  File "C:\Users\xxx\PycharmProjects\pytorch.rl.learning\predl\base.py", line 61, in train
    total_reward = self._loop()
  File "C:/Users/xxx/PycharmProjects/pytorch.rl.learning/predl/table/sarsa.py", line 17, in _loop
    action = self.policy()
  File "C:\Users\xxx\PycharmProjects\pytorch.rl.learning\predl\base.py", line 38, in policy
    return getattr(self, self._policy)
  File "C:\Users\xxx\PycharmProjects\pytorch.rl.learning\predl\table\table_base.py", line 54, in epsilon_greedy
    action = self.argmax(self.q_table[self.state])
  File "C:\Users\xxx\PycharmProjects\pytorch.rl.learning\predl\base.py", line 84, in argmax
    return x.max(dim=0)[1][0]
IndexError: invalid index of a 0-dim tensor. Use tensor.item() to convert a 0-dim tensor to a Python number

**Comment by moskomule** [comment]
Hi, I did this project long before, so APIs of PyTorch has changed since then.
I don't plan to maintain this project anymore, so if necessary, please change the codes according to the latest APIs. PRs are welcome.

**Comment by Jungmo** [comment]
@moskomule Thanks a lot for your comment!

**Comment by Jungmo** [comment]
Modifying "return x.max(dim=0)[1][0]" to "return x.max(dim=0)[1].item()" is working.
